# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# Hourly scraping
name: crawl_water_data

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #schedule:
  #    - cron:  '0 */4 * * *' #Runs on the 0, 4, 8, 12, 16 and 20th hour
      #At minute 0 past every 4th hour https://crontab.guru/every-4-hours

jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: install dependencies
        run: sudo apt-get install libcurl4-openssl-dev libgeos-dev libudunits2-dev

    # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("jsonlite",dependencies = T)'
          R -e 'install.packages("rlist",dependencies = T)'
        
    # Run R script
      - name: get_water_quality
        run: Rscript get_water_quality.R
      
 # Add new files in data folder, commit along with other modified files, push
      - name: push the water_quality_data to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add water_quality_data
          git commit -am "GH ACTION water quality $(date)"
          git push https://${{github.actor}}:${{secrets.LERY}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
          #git commit water_quality_data --allow-empty -m 'add crawl: ${{github.run_number}}' || echo "No changes to commit"
  
  # Run R script
      - name: get_hydrological
        run: Rscript get_hydrological.R
      
 # Add new files in data folder, commit along with other modified files, push
      - name: push the hydrological_data to GitHub
        run: |
         git config --local user.email ly_ding@126.com
         git config --local user.name Otoliths
         git add hydrological_data
         git commit -am "GH ACTION hydrological $(date)"
         git push https://${{github.actor}}:${{secrets.LERY}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
        
        #env:
         #REPO_KEY: ${{secrets.LERY}}
         #username: github-actions
       
       #git commit hydrological_data --allow-empty -m 'add crawl: ${{github.run_number}}' || echo "No changes to commit"
       
      
      
